### ISSUE TITLE
Add Python 3.7 to Tox and Travis configuration

### ISSUE THREAD

**Issue by justinmayer** [justinmayer/django-elevate#7]
As far as Travis is concerned, the officially-sanctioned method of supporting Python 3.7 appears to be something like:
```
matrix:
  include:
    - python: 3.7
      sudo: true
      dist: xenial
      env:
        - TOX_ENV=py37
```
c.f., https://github.com/travis-ci/travis-ci/issues/9815#issue-336465122
